kind: Service
apiVersion: v1
metadata:
  name: hello
  namespace: microservices
  labels:
    app: hello
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - protocol: TCP
    name: http-3000
    port: 3000
    targetPort: 3000